name: Generate package RST
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - specify_azure_ml_component
jobs:
  sphinx-apidoc :
    runs-on: ubuntu-latest
    steps:

    - name: git-checkout
      uses: actions/checkout@v2

    # ===========================Setup python================================
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8

    # ===========================Install requirements================================
    - name: Install requirements
      run: |
        pip install --upgrade pip==20.2
        pip install sphinx==1.5.5 sphinx_rtd_theme==0.5.0

    # ===========================Generate sphinx================================
    - name: Generate sphinx apidoc
      run: |
        sphinx-apidoc -f --module-first . -o ./doc setup.py
      working-directory: ./generated_package/example-assets

    # ===========================Push================================
    - name: Commit report
      run: |
        git config --global user.name 'henu_rz@163.com'
        git config --global user.email 'henu_rz@users.noreply.github.com'
        git add .
        git commit -m "Update doc"
        git push origin ${GITHUB_REF##*/}:reference_doc